import smtplib
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from dotenv import load_dotenv

load_dotenv()

def send_summary_email(summary, output_filename):
    # Send a summary email with the finance report
    print("Sending summary email...")
    sender_email = os.getenv("EMAIL_SENDER")
    receiver_email = os.getenv("EMAIL_RECEIVER")
    password = os.getenv("EMAIL_PASSWORD")

    if not all([sender_email, receiver_email, password]):
        print("⚠️ Email credentials are not fully set in the .env file.")
        return
    
    print("✓ Email credentials loaded successfully.")

    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = receiver_email
    msg['Subject'] = "Finance Dashboard - Daily Report"
    print("✓ Prepared email headers.")
    body = f"""
    Finance Dashboard Report

    Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    """
    print("✓ Added generation date to email body.")
    body += f"""
    SUMMARY
    -------
    Income:      €{summary['income']:>10.2f}
    Expenses:    €{summary['expenses']:>10.2f}
    Net Savings: €{summary['net']:>10.2f}
    TOP SPENDING CATEGORY

    {summary['biggest_expense']['description']}: €{summary['biggest_expense']['amount']:.2f}

    BREAKDOWN
    """
    for category, amount in sorted(summary["by_category"].items(), key=lambda x: x[1], reverse=True)[:5]:
        body += f"\n{category:.<25} €{amount:>8.2f}"
    body += f"""
    Reports saved:
    - Excel: {output_filename}
    - Google Sheets: Updated
    - Local: reports/ folder

    ---
    Auto-generated by Finance Dashboard
    """
    print("✓ Prepared summary email body.")
    msg.attach(MIMEText(body, 'plain'))
    print("✓ Prepared summary email content.")
    try:
        # use SMTP_SSL for port 465
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(sender_email, password)
            server.send_message(msg)
        print("✓ Summary email sent successfully.")
    except Exception as e:
        print(f"⚠️ Failed to send summary email: {e}")